### ISSUE TITLE
Add directory example

### ISSUE THREAD

**Issue by gforge** [fjc0k/vscode-generate-index#7]
A minor tip for improving the Readme, add an example that allows users to add directories and not only files:

`// @index(['./*/index.ts(|x)', './*.ts(|x)'], f => `export * from '${f.path.replace(/\/index$/, "")}';`)`

The code finds `ts` and `tsx` files at the local directory and also looks for directories with `index.ts` or `index.tsx` which is also why we need the `replace` to drop the 'index' string at the end.

**Comment by fjc0k** [comment]
👍 

Added 3 new examples:

https://github.com/fjc0k/vscode-generate-index#usage

**Comment by gforge** [comment]
Thanks, and btw, your extension is simply awesome! Keep up the good work!
